# @file Dockerfile
# @description Patroni + PostgreSQL Dockerfile
# @author YanYuCloudCube Team <admin@0379.email>
# @version v1.0.0
# @created 2026-03-14
# @updated 2026-03-14
# @status stable
# @license MIT
# @copyright Copyright (c) 2026 YanYuCloudCube Team
# @tags docker,patroni,postgresql

FROM postgres:15-alpine

RUN apk add --no-cache python3 py3-pip
RUN pip3 install patroni[etcd3]

COPY sql /app/sql

CMD ["patroni", "/etc/patroni/patroni.yml"]